import os
from dotenv import load_dotenv
load_dotenv()
USE_FIRESTORE_EMULATOR = os.getenv("USE_FIRESTORE_EMULATOR", "false").lower() == "true"
FIRESTORE_EMULATOR_HOST = os.getenv("FIRESTORE_EMULATOR_HOST")
PROJECT_ID = os.getenv("FIREBASE_PROJECT_ID")
CREDENTIALS_PATH = os.getenv("FIREBASE_CREDENTIALS_PATH")
STORAGE_BUCKET = os.getenv("STORAGE_BUCKET") or os.getenv("FIREBASE_STORAGE_BUCKET")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
EMAIL_SENDER = os.getenv("EMAIL_SENDER", "noreply@example.com")
FIREBASE_AUTH_EMULATOR_HOST = os.getenv("FIREBASE_AUTH_EMULATOR_HOST")
FIREBASE_STORAGE_EMULATOR_HOST = os.getenv("FIREBASE_STORAGE_EMULATOR_HOST")
